# Generated by Django 5.2.7 on 2025-10-29 00:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cursos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="curso",
            name="inscriptos",
            field=models.IntegerField(default=0),
        ),
    ]
