# Generated by Django 5.2.7 on 2025-10-24 00:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alumnos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="alumno",
            name="activo",
            field=models.BooleanField(default=True),
        ),
    ]
