# Generated by Django 5.2.7 on 2025-10-29 00:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alumnos", "0002_alumno_activo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alumno",
            name="activo",
            field=models.BooleanField(default=False),
        ),
    ]
