# Generated by Django 5.2.7 on 2025-11-06 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alumnos", "0003_alter_alumno_activo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profesor",
            fields=[
                (
                    "alumno_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="alumnos.alumno",
                    ),
                ),
                ("turno", models.CharField(max_length=45)),
            ],
            bases=("alumnos.alumno",),
        ),
    ]
