# Generated by Django 5.2.7 on 2025-11-12 20:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("alumnos", "0004_profesor"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profesor",
            options={"verbose_name_plural": "Profesores"},
        ),
    ]
